list: $/smony/feedback/models/calls/columns.yaml
modelClass: Smony\Feedback\Models\Calls
title: Calls
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'smony/feedback/calls/update/:id'
